
version: "3"
services: 
  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    environment: 
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db123
    ports: 
      - "5432:5432"
  server:
    image: my-server
    container_name: server
    working_dir: /usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    command: npm run server
    depends_on:
       - db