const defaultShip =
  "'#0000', '#0000', '#0000', '#0000', '#0000', '#0000', '#0000', '#0000', '#0000', '#0000', '#0000', '#b90828ff', '#e40520ff', '#0000', '#0000', '#0000', '#0000', '#0000', '#860524ff', '#17b908ff', '#05e41bff', '#f8032fff', '#0000', '#0000', '#0000', '#79021fff', '#057902ff', '#0844b9ff', '#0348f8ff', '#17f803ff', '#f8032fff', '#0000', '#0000', '#79021fff', '#057902ff', '#17b908ff', '#05e41bff', '#17f803ff', '#f8032fff', '#0000', '#0000', '#79021fff', '#057902ff', '#17b908ff', '#05e41bff', '#17f803ff', '#f8032fff', '#0000', '#0000', '#0000', '#8f8a8aff', '#da8403ff', '#da8403ff', '#c1bdbdff', '#0000', '#0000', '#0000', '#0000', '#0000', '#da8403ff', '#da8403ff', '#0000', '#0000', '#0000'";

const queryTables = {
  player: `CREATE TABLE IF NOT EXISTS player (
  id INT GENERATED ALWAYS AS IDENTITY  PRIMARY KEY,
  name CHARACTER VARYING(30) UNIQUE NOT NULL,
  email CHARACTER VARYING(60) UNIQUE NOT NULL,
  password TEXT  NOT NULL,
  coins INT NOT NULL DEFAULT 20,
  active_ship_id INT,
  following_id INT[]
);`,

  store: `CREATE TABLE IF NOT EXISTS store (
  store_id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 101)  PRIMARY KEY UNIQUE
);`,

  ship: `CREATE TABLE IF NOT EXISTS ship (
  ship_id INT GENERATED ALWAYS AS IDENTITY  PRIMARY KEY,
  player_id INT REFERENCES player(id) ON DELETE CASCADE,
  pixels TEXT[] NOT NULL DEFAULT ARRAY[${defaultShip}],
  store_id INT REFERENCES store(store_id),
  from_other_id INT,
  price INT NOT NULL DEFAULT 20
);`,

  likes: `CREATE TABLE IF NOT EXISTS likes (
  id INT GENERATED ALWAYS AS IDENTITY  PRIMARY KEY UNIQUE,
  store_id INT REFERENCES store(store_id) ON DELETE CASCADE,
  player_id INT REFERENCES player(id) ON DELETE CASCADE
);`,

  score: `CREATE TABLE IF NOT EXISTS score (
  playername CHARACTER VARYING(30) REFERENCES player(name) ON DELETE CASCADE,
  points INT NOT NULL DEFAULT 0,
  PRIMARY KEY (playername)
);`,
};
export { queryTables };
