# nginx/Dockerfile
# FROM nginx:alpine

# # Copia el archivo de configuración de Nginx
# COPY default.conf /etc/nginx/conf.d/default.conf

# # Copia el certificado SSL y la clave privada
# COPY certificate.crt /etc/ssl/certs/certificate.crt
# COPY private.key /etc/ssl/private/private.key


# --------------------


FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf
